# Generated by Django 2.0.7 on 2018-08-10 01:05

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Descripition')),
                ('start_time', models.TimeField(default=datetime.time(7, 0), verbose_name='Start time')),
                ('end_time', models.TimeField(default=datetime.time(7, 0), verbose_name='End time')),
                ('date', models.DateField(verbose_name='Date')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
            ],
        ),
    ]
