# Generated by Django 2.0.7 on 2018-08-11 17:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180812_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 11, 17, 12, 56, 986029, tzinfo=utc), verbose_name='date published'),
        ),
    ]
