# Generated by Django 2.0.7 on 2018-08-12 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180812_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 12, 14, 14, 48, 103615, tzinfo=utc), verbose_name='date published'),
        ),
    ]
